// services/r2.ts
// The church's own media, served from a public Cloudflare R2 bucket.
//
// TWO MANIFESTS, ONE SHAPE. `manifests/audio-manifest.json` lists the mp3s and
// `manifests/documents-manifest.json` lists the pdfs; both are
// `{ items: [{ title, sourceFilename, url, sizeBytes }] }`. The bucket is
// public, so these are plain unauthenticated GETs — no key, no signing, and
// nothing here should ever grow one: the R2 access keys in .env belong to the
// UPLOAD side of this system, not the app.
//
// CACHING follows services/youtube.ts exactly — AsyncStorage, one
// `{ items, fetchedAt }` blob per manifest, a TTL to decide when to refetch —
// with one addition it needed and youtube.ts does not: a STALE-ON-ERROR read.
// A YouTube fetch that fails leaves a screen that can honestly say "couldn't
// load"; these manifests back the only content those two screens have, so
// showing yesterday's list beats showing nothing when the network is down.
// Hence readCache() is called twice per fetch: once for a fresh hit, once
// again as a fallback after a failure, ignoring the TTL the second time.
//
// TTL is 6 hours rather than youtube.ts's 1. These files change when someone
// uploads a sermon recording — days apart, not minutes — and every refetch is
// a full list of every item the church has ever published (546 audio entries
// today), so a shorter window would spend real bandwidth on an answer that is
// almost always identical.

import AsyncStorage from '@react-native-async-storage/async-storage';

/**
 * Bucket root. Comes from .env so the dev and production buckets can differ
 * without a code change; the literal is the current public bucket and exists
 * so a fresh clone with no .env still shows real content instead of an empty
 * screen it would be easy to misread as a bug.
 */
const R2_BASE = (
  process.env.EXPO_PUBLIC_R2_PUBLIC_DEV_ID ?? 'https://pub-1f3bc94509404247b0a4a8cf226e3b9a.r2.dev'
)
  .trim()
  .replace(/\/+$/, '');

const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // 6 hours — see note above

/** One entry in either manifest, exactly as it appears in the JSON. */
export interface R2Item {
  /** Human-readable, already cleaned up by the upload pipeline. */
  title: string;
  /** The original file name. Kept for provenance/debugging, not displayed. */
  sourceFilename: string;
  /** Absolute URL to the media file. See normalizeUrl for the encoding catch. */
  url: string;
  sizeBytes: number;
  /**
   * ISO-like local timestamp ('2026-03-08T08:18:09'), added by a one-time
   * enrichment pass over the source files. OPTIONAL, and genuinely so: 521 of
   * 546 audio items carry one, 25 do not. Everything that sorts on it must
   * decide where an undated item goes rather than assuming one exists — see
   * byRecency in utils/audioGrouping.ts, which sends them to the end.
   */
  date?: string;
}

export type R2ManifestKind = 'audio' | 'documents';

const MANIFEST_PATH: Record<R2ManifestKind, string> = {
  audio: '/manifests/audio-manifest.json',
  documents: '/manifests/documents-manifest.json',
};

// VERSIONED. The v1 blobs on devices predate the manifest's `date` field, and
// a 6-hour TTL means an app updated mid-window would sort a dateless cached
// list until it expired — i.e. the recency ordering would silently not work on
// exactly the devices that had used the app most recently. Bumping the key
// retires those blobs immediately instead.
const cacheKey = (kind: R2ManifestKind) => `r2:manifest:v2:${kind}`;

/**
 * THE ENCODING CATCH, and why this is not just `encodeURI`.
 *
 * The live manifest contains RAW SPACES in its urls
 * (".../audio/2019 Prophetic Prayer.mp3" — 482 of 546 entries today), while
 * the documented example shows them percent-encoded. Both have to work:
 *
 *   - raw spaces must be encoded, or iOS's NSURL rejects the string outright
 *     and both the audio player and Linking.openURL fail silently
 *   - already-encoded urls must NOT be encoded again — encodeURI escapes '%'
 *     itself, so a second pass turns %20 into %2520 and the request 404s
 *
 * decode-then-encode normalizes both cases to the same output. A malformed
 * escape sequence makes decodeURI throw, so that case falls back to using the
 * url exactly as the manifest gave it — a url we cannot reason about is
 * better passed through untouched than mangled.
 */
export function normalizeUrl(url: string): string {
  try {
    return encodeURI(decodeURI(url));
  } catch {
    return url;
  }
}

interface CacheBlob {
  items: R2Item[];
  fetchedAt: number;
}

async function readCache(kind: R2ManifestKind): Promise<CacheBlob | null> {
  try {
    const raw = await AsyncStorage.getItem(cacheKey(kind));
    if (!raw) return null;
    const blob = JSON.parse(raw) as CacheBlob;
    if (!Array.isArray(blob?.items)) return null;
    return blob;
  } catch {
    return null;
  }
}

/**
 * Defensive parse. This JSON is generated by a separate upload pipeline and
 * lands on a device that may have cached an older version of its shape, so
 * anything missing the two fields the UI actually needs (a title to show and a
 * url to open) is dropped rather than rendered as a blank, untappable row.
 */
function parseItems(json: unknown): R2Item[] {
  const items = (json as { items?: unknown })?.items;
  if (!Array.isArray(items)) return [];
  return items
    .filter(
      (i): i is R2Item =>
        !!i && typeof i.title === 'string' && i.title.length > 0 && typeof i.url === 'string'
    )
    .map((i) => ({
      title: i.title,
      sourceFilename: typeof i.sourceFilename === 'string' ? i.sourceFilename : '',
      url: normalizeUrl(i.url),
      sizeBytes: typeof i.sizeBytes === 'number' ? i.sizeBytes : 0,
      // Anything that is not a non-empty string is dropped to undefined, so
      // downstream code has exactly two cases to handle instead of also
      // guarding against '' and null.
      date: typeof i.date === 'string' && i.date.length > 0 ? i.date : undefined,
    }));
}

export interface ManifestResult {
  items: R2Item[];
  /** True when the network failed and these items came from a stale cache. */
  fromStaleCache: boolean;
}

/**
 * Fetch a manifest, preferring a fresh cache entry. Throws only when the
 * network fails AND there is no cache at all to fall back on — that is the one
 * case where the caller genuinely has nothing to show.
 */
export async function fetchManifest(kind: R2ManifestKind): Promise<ManifestResult> {
  const cached = await readCache(kind);
  if (cached && Date.now() - cached.fetchedAt < CACHE_TTL_MS) {
    return { items: cached.items, fromStaleCache: false };
  }

  try {
    const res = await fetch(`${R2_BASE}${MANIFEST_PATH[kind]}`);
    if (!res.ok) throw new Error(`R2 ${kind} manifest: HTTP ${res.status}`);
    const items = parseItems(await res.json());
    await AsyncStorage.setItem(
      cacheKey(kind),
      JSON.stringify({ items, fetchedAt: Date.now() } satisfies CacheBlob)
    );
    return { items, fromStaleCache: false };
  } catch (e) {
    // Offline, or the bucket is unreachable. An EXPIRED cache is still the
    // church's real library and is worth far more than an error screen.
    if (cached) {
      console.warn(`R2 ${kind} manifest fetch failed, serving stale cache:`, e);
      return { items: cached.items, fromStaleCache: true };
    }
    throw e;
  }
}

/** "12.4 MB" — the only size units these files ever land in. */
export function formatBytes(bytes: number): string {
  if (!bytes || bytes < 0) return '';
  const mb = bytes / (1024 * 1024);
  if (mb < 1) return `${Math.max(1, Math.round(bytes / 1024))} KB`;
  return `${mb < 10 ? mb.toFixed(1) : Math.round(mb)} MB`;
}
